name: Hello World

on:
    push:
        

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Install pnpm
              uses: pnpm/action-setup@v2.4.0
              with:
                    version: 8
                    run_install: false
           
            - name: Install dependencies
              run: npm install

            - name: Build
              run: npm run build