name: Hello World

on:
    push:
        

jobs:
    hello-world:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Hello World
              run: echo "Hello World"